CREATE TABLE "main"."key" (
  "id"         INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  "secret"     TEXT NOT NULL UNIQUE,
  "access_key" TEXT NOT NULL UNIQUE,
  "created_at" INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER key_updated_at BEFORE UPDATE ON "main"."key" FOR EACH ROW
BEGIN
  UPDATE key SET updated_at = CURRENT_TIMESTAMP WHERE id = new.id;
END;
